openapi: 3.0.0
info:
  title: Big Buck Bunny Player API
  description: API liée au test technique mis en place par l'équipe OnePlayer et liée à un lecteur vidéo lançant le contenu Big Buck Bunny
  version: 1.0.0
servers:
  - url: https://oneplayer-tech-test.herokuapp.com/
    description: Main server
paths:
  /scenes:
    get:
      summary: Returns a list of all the scenes existing with minimal data
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /crew:
    get:
      summary: Returns a list of persons from the crew who worked on the project with their names, roles, etc.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /bonusImages:
    get:
      summary: Returns a list of all the scenes existing with minimal data
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /scene/{timecode}:
    get:
      summary: Returns a list of details of a specific scene corresponding to the given timecode
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - name: timecode
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
